import { Module } from '@nestjs/common';
import { z, type ZodSchema } from 'zod';

import { createCatalogModule } from './catalog-factory';

// Re-usable partial schema
const i18nSchema = z.record(z.string(), z.string());

// 25+ catalog modules with a single config each
const catalogs = [
  {
    table: 'service_categories',
    route: 'service-categories',
    create: z.object({ name_i18n: i18nSchema, icon: z.string().optional(), color: z.string().optional(), sort_order: z.number().int().default(0) }),
    update: z.object({ name_i18n: i18nSchema.optional(), icon: z.string().optional(), color: z.string().optional(), sort_order: z.number().int().optional() }),
  },
  {
    table: 'services',
    route: 'services',
    create: z.object({
      category_id: z.string().uuid().optional(),
      name_i18n: i18nSchema,
      description_i18n: i18nSchema.optional(),
      price_uzs: z.number().int().nonnegative(),
      duration_min: z.number().int().positive().default(30),
      doctor_required: z.boolean().default(true),
      room_type: z.string().optional(),
      is_insurance_covered: z.boolean().default(false),
      sku: z.string().optional(),
      sort_order: z.number().int().default(0),
    }),
    update: z.object({
      category_id: z.string().uuid().nullish(),
      name_i18n: i18nSchema.optional(),
      description_i18n: i18nSchema.optional(),
      price_uzs: z.number().int().nonnegative().optional(),
      duration_min: z.number().int().positive().optional(),
      doctor_required: z.boolean().optional(),
      room_type: z.string().optional(),
      is_insurance_covered: z.boolean().optional(),
      sort_order: z.number().int().optional(),
    }),
  },
  {
    table: 'rooms',
    route: 'rooms',
    create: z.object({
      number: z.string(),
      floor: z.number().int().optional(),
      name_i18n: i18nSchema.optional(),
      type: z.string().optional(),
      capacity: z.number().int().positive().default(1),
      hourly_price_uzs: z.number().int().optional(),
      daily_price_uzs: z.number().int().optional(),
      amenities: z.array(z.string()).optional(),
    }),
    update: z.object({
      floor: z.number().int().optional(),
      name_i18n: i18nSchema.optional(),
      type: z.string().optional(),
      capacity: z.number().int().positive().optional(),
      hourly_price_uzs: z.number().int().optional(),
      daily_price_uzs: z.number().int().optional(),
      amenities: z.array(z.string()).optional(),
      status: z.string().optional(),
    }),
  },
  { table: 'room_tariffs', route: 'room-tariffs',
    create: z.object({ room_id: z.string().uuid(), tariff_name: z.string(), price_uzs: z.number().int(), duration_unit: z.enum(['hour','day','week']).default('day') }),
    update: z.object({ tariff_name: z.string().optional(), price_uzs: z.number().int().optional() }),
  },
  { table: 'diagnostic_categories', route: 'diagnostic-categories',
    create: z.object({ name_i18n: i18nSchema, icon: z.string().optional(), sort_order: z.number().int().default(0) }),
    update: z.object({ name_i18n: i18nSchema.optional(), icon: z.string().optional(), sort_order: z.number().int().optional() }),
  },
  { table: 'diagnostic_preparations', route: 'diagnostic-preparations',
    create: z.object({ name_i18n: i18nSchema, instructions_i18n: i18nSchema, duration_before_hours: z.number().int().optional() }),
    update: z.object({ name_i18n: i18nSchema.optional(), instructions_i18n: i18nSchema.optional(), duration_before_hours: z.number().int().optional() }),
  },
  { table: 'diagnostic_equipment', route: 'diagnostic-equipment',
    create: z.object({ name: z.string(), manufacturer: z.string().optional(), model: z.string().optional(), serial_number: z.string().optional(), room_id: z.string().uuid().optional() }),
    update: z.object({ manufacturer: z.string().optional(), model: z.string().optional(), status: z.string().optional(), next_maintenance_due: z.string().datetime().optional() }),
  },
  { table: 'diagnostic_types', route: 'diagnostic-types',
    create: z.object({
      category_id: z.string().uuid(), code: z.string().optional(),
      name_i18n: i18nSchema, description_i18n: i18nSchema.optional(),
      default_equipment_id: z.string().uuid().optional(), preparation_id: z.string().uuid().optional(),
      price_uzs: z.number().int(), duration_min: z.number().int().default(30),
      result_kind: z.enum(['image_plus_report','report_only','numeric']).default('report_only'),
    }),
    update: z.object({ name_i18n: i18nSchema.optional(), price_uzs: z.number().int().optional(), duration_min: z.number().int().optional() }),
  },
  { table: 'lab_test_categories', route: 'lab-test-categories',
    create: z.object({ name_i18n: i18nSchema }), update: z.object({ name_i18n: i18nSchema.optional() }) },
  { table: 'lab_tests', route: 'lab-tests',
    create: z.object({ category_id: z.string().uuid().optional(), code: z.string().optional(), name_i18n: i18nSchema, price_uzs: z.number().int(), unit: z.string().optional(), reference_range_male: z.string().optional(), reference_range_female: z.string().optional() }),
    update: z.object({ name_i18n: i18nSchema.optional(), price_uzs: z.number().int().optional() }),
  },
  { table: 'medication_categories', route: 'medication-categories',
    create: z.object({ name_i18n: i18nSchema }), update: z.object({ name_i18n: i18nSchema.optional() }) },
  { table: 'medications', route: 'medications',
    create: z.object({ category_id: z.string().uuid().optional(), name: z.string(), manufacturer: z.string().optional(), strength: z.string().optional(), form: z.string().optional(), price_uzs: z.number().int(), stock: z.number().int().default(0), barcode: z.string().optional() }),
    update: z.object({ price_uzs: z.number().int().optional(), stock: z.number().int().optional() }),
  },
  { table: 'suppliers', route: 'suppliers',
    create: z.object({ name: z.string(), contact_person: z.string().optional(), phone: z.string().optional(), email: z.string().email().optional() }),
    update: z.object({ name: z.string().optional(), phone: z.string().optional() }),
  },
  { table: 'expense_categories', route: 'expense-categories',
    create: z.object({ name_i18n: i18nSchema, icon: z.string().optional(), color: z.string().optional() }),
    update: z.object({ name_i18n: i18nSchema.optional() }),
  },
  { table: 'payment_methods_catalog', route: 'payment-methods',
    create: z.object({ name_i18n: i18nSchema, type: z.enum(['cash','card','transfer','insurance','click','payme','uzum','kaspi','humo','uzcard','stripe']), commission_percent: z.number().default(0), provider_kind: z.string().optional() }),
    update: z.object({ commission_percent: z.number().optional(), is_active: z.boolean().optional() }),
  },
  { table: 'discount_rules', route: 'discount-rules',
    create: z.object({ name_i18n: i18nSchema, type: z.enum(['percent','fixed']), value: z.number(), conditions: z.record(z.unknown()).optional(), valid_from: z.string().datetime().optional(), valid_to: z.string().datetime().optional() }),
    update: z.object({ value: z.number().optional(), is_active: z.boolean().optional() }),
  },
  { table: 'insurance_companies', route: 'insurance-companies',
    create: z.object({ name: z.string(), contract_no: z.string().optional(), commission_percent: z.number().default(0) }),
    update: z.object({ name: z.string().optional(), commission_percent: z.number().optional() }),
  },
  { table: 'referral_partners', route: 'referral-partners',
    create: z.object({ name: z.string(), type: z.string().optional(), commission_percent: z.number().default(0) }),
    update: z.object({ commission_percent: z.number().optional() }),
  },
  { table: 'document_templates', route: 'document-templates',
    create: z.object({ kind: z.enum(['receipt','prescription','certificate','invoice','discharge_summary']), name_i18n: i18nSchema, content_html_i18n: i18nSchema, variables: z.array(z.string()).default([]) }),
    update: z.object({ content_html_i18n: i18nSchema.optional() }),
  },
  { table: 'sms_templates', route: 'sms-templates',
    create: z.object({ key: z.string(), content_i18n: i18nSchema, variables: z.array(z.string()).default([]), trigger_event: z.string().optional() }),
    update: z.object({ content_i18n: i18nSchema.optional(), is_active: z.boolean().optional() }),
  },
  { table: 'email_templates', route: 'email-templates',
    create: z.object({ key: z.string(), subject_i18n: i18nSchema, content_html_i18n: i18nSchema, variables: z.array(z.string()).default([]), trigger_event: z.string().optional() }),
    update: z.object({ subject_i18n: i18nSchema.optional(), content_html_i18n: i18nSchema.optional() }),
  },
  { table: 'working_hours', route: 'working-hours',
    create: z.object({ day_of_week: z.number().int().min(0).max(6), open_from: z.string().optional(), close_to: z.string().optional(), is_closed: z.boolean().default(false) }),
    update: z.object({ open_from: z.string().optional(), close_to: z.string().optional(), is_closed: z.boolean().optional() }),
  },
  { table: 'holidays', route: 'holidays',
    create: z.object({ date: z.string(), name_i18n: i18nSchema, is_closed: z.boolean().default(true), recurring_yearly: z.boolean().default(false) }),
    update: z.object({ name_i18n: i18nSchema.optional(), is_closed: z.boolean().optional() }),
  },
  { table: 'custom_roles', route: 'custom-roles',
    create: z.object({ name: z.string(), description: z.string().optional(), permissions: z.record(z.unknown()).default({}), base_role: z.string().default('staff') }),
    update: z.object({ name: z.string().optional(), permissions: z.record(z.unknown()).optional() }),
  },
  { table: 'marketing_segments', route: 'marketing-segments',
    create: z.object({ name: z.string(), description: z.string().optional(), filter_query: z.record(z.unknown()), is_dynamic: z.boolean().default(true) }),
    update: z.object({ name: z.string().optional(), filter_query: z.record(z.unknown()).optional() }),
  },
  { table: 'loyalty_rules', route: 'loyalty-rules',
    create: z.object({ name: z.string(), trigger_event: z.string(), points_awarded: z.number().int(), condition: z.record(z.unknown()).optional() }),
    update: z.object({ points_awarded: z.number().int().optional(), is_active: z.boolean().optional() }),
  },
];

const catalogModules = catalogs.map((c) =>
  createCatalogModule({
    table: c.table,
    route: c.route,
    createSchema: c.create as unknown as ZodSchema<unknown>,
    updateSchema: c.update as unknown as ZodSchema<unknown>,
  }),
);

@Module({
  imports: catalogModules,
})
export class CatalogModule {}
